name: pytest

on: [push, pull_request]

jobs:
  test-on-env:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python-version: [ "3.8", "3.9", "3.10" ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Test with pytest
      run: |
        pip install pytest
        pytest tests
